#!/usr/bin/env python3
"""Generate themes/<name>.ini for every built-in Textual theme.

Each Textual theme name (used for ``TEXTUAL_THEME`` / ``zstyle
':zsh-ai:view' theme``) gets a matching Rich markdown theme here, so the
one name themes both bin/mdview (Textual, native) and bin/mdrender (Rich,
via these files). Palettes are read straight from Textual so the colors
match the viewer.

Re-run after upgrading Textual:

    .venv/bin/python themes/generate.py
"""

from __future__ import annotations

from pathlib import Path
from typing import Optional

from textual.theme import BUILTIN_THEMES

# Best-match Pygments style per theme for fenced code blocks. Themes
# without a close match fall back by light/dark (see below).
CODE_THEMES = {
    "dracula": "dracula",
    "nord": "nord",
    "monokai": "monokai",
    "gruvbox": "gruvbox-dark",
    "solarized-dark": "solarized-dark",
    "solarized-light": "solarized-light",
    "atom-one-dark": "one-dark",
    "tokyo-night": "one-dark",
    "ansi-dark": "ansi_dark",
    "ansi-light": "ansi_light",
}

HEADER = """\
# {name} theme for bin/mdrender (Rich), generated by themes/generate.py
# from Textual's built-in `{name}` palette. The same name themes both
# mdview (TEXTUAL_THEME) and mdrender (this file). [styles] layers on top
# of Rich's defaults (inherit=True); [code] is the Pygments style used
# for fenced code blocks.
"""


def rich_color(value: Optional[str]) -> Optional[str]:
    """Translate a Textual color token to something Rich's Style.parse
    accepts, or None if it has no concrete color. Textual's ANSI themes
    use ``ansi_<name>`` tokens — strip the prefix so they map to Rich's
    own ANSI color names (i.e. the terminal palette); ``ansi_default`` /
    ``transparent`` become None (use the terminal's default)."""
    if not value or value == "transparent":
        return None
    if value.startswith("ansi_"):
        rest = value[len("ansi_") :]
        return None if rest == "default" else rest
    return value


def main() -> None:
    out_dir = Path(__file__).parent
    for name, theme in BUILTIN_THEMES.items():
        cs = theme.to_color_system().generate()
        primary = rich_color(cs.get("primary")) or "default"
        secondary = rich_color(cs.get("secondary")) or primary
        accent = rich_color(cs.get("accent")) or secondary
        warning = rich_color(cs.get("warning")) or accent
        surface = rich_color(cs.get("surface"))
        code = CODE_THEMES.get(name, "monokai" if theme.dark else "default")

        on_surface = f" on {surface}" if surface else ""
        styles = {
            "markdown.h1": "bold underline",
            "markdown.h2": f"underline {primary}",
            "markdown.h3": f"bold {primary}",
            "markdown.h4": f"italic {primary}",
            "markdown.h5": "italic",
            "markdown.h6": "dim",
            "markdown.h7": "dim italic",
            "markdown.code": f"bold {secondary}{on_surface}",
            "markdown.code_block": f"{secondary}{on_surface}",
            "markdown.block_quote": accent,
            "markdown.link": secondary,
            "markdown.link_url": f"underline {secondary}",
            "markdown.item.bullet": f"bold {primary}",
            "markdown.item.number": secondary,
            "markdown.list": secondary,
            "markdown.hr": "dim",
            "markdown.kbd": f"bold {warning}",
            "markdown.table.border": secondary,
            "markdown.table.header": f"not bold {secondary}",
        }
        body = "\n".join(f"{k} = {v}" for k, v in styles.items())
        text = (
            HEADER.format(name=name) + f"\n[styles]\n{body}\n\n[code]\ntheme = {code}\n"
        )
        (out_dir / f"{name}.ini").write_text(text)
        print(f"wrote {name}.ini")


if __name__ == "__main__":
    main()
